name: Cross compile binaries

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build for ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux (x86_64)
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os-name: Linux (aarch64)
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - os-name: macOS (aarch64)
            runs-on: macos-latest
            target: aarch64-apple-darwin

          - os-name: Windows (x86_64)
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Build a binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: knot-downloader
          target: ${{ matrix.platform.target }}
          changes-file: ""
